version: '3'
services:
  app:
    container_name: bus-booking-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bus
    depends_on:
      - mongo

  mongo:
    container_name: bus-booking-mongo
    image: mongo
    ports:
      - "27017:27017"